### ISSUE TITLE
Landing page: link del footer mancanti

### ISSUE THREAD

**Issue by giuliocamtv** [camtv/funnel#1]
In fondo alla pagina https://camtv.github.io/funnel/01-landingpage/index.html sembrano mancare dei link: si vedono infatti le voci di footer "Privacy Policy, Earnings Disclaimer, Guarantee Terms & Conditions" senza link:

![funnel01](https://user-images.githubusercontent.com/64125620/79981114-69a2c780-84a4-11ea-9b88-35234ab57e3b.png)

**Comment by PaoloBrach** [comment]
ho controllato e non erano stati inseriti nemmeno nel design originale, io credo si possano anche rimuovere. Vedo cosa ne pensa Alessio.

**Comment by PaoloBrach** [comment]
Alessio mi ha confermato di inserire quelli presenti sul sito cam.tv, procedo alla modifica

**Comment by PaoloBrach** [comment]
Link aggiunti come da indicazioni di Alessio. Aggiunto anche mailto alla mail support@cam.tv

**Comment by giuliocamtv** [comment]
verificato, chiudo il ticket
