### ISSUE TITLE
Landind page: pagamento mancante e reindirizzamento errato

### ISSUE THREAD

**Issue by giuliocamtv** [camtv/funnel#2]
Dopo aver compilato il form dalla pagina Landing Page (https://camtv.github.io/funnel/01-landingpage/index.html) e confermato l'acquisto
- manca la possibilità di pagare e 
- si viene reindirizzati alla pagina GitHub 404: https://camtv.github.io/?name=dfgfdgdf&email=fgdfgfdg@getnada.com&emailck=fgdfgfdg@getnada.com&address=sdsd&citta=dfdf&cap=4343&tel=32&naz=ITA&offerta=offerta

Pagina di errore:
![funnel02](https://user-images.githubusercontent.com/64125620/79981365-d74ef380-84a4-11ea-9d7f-596d711610a7.png)

**Comment by PaoloBrach** [comment]
Il reindirizzamento sbagliato credo si possa correggere solo modificando il parametro della chiamata. Non ho ben capito però cosa significa "manca la possibilità di pagare". Cioè, non appare proprio il popup camtv pay? ricordo che il controllo spam blocca la transazione se la mail inserita per l'ordine è fittizia o in balcklist

**Comment by giuliocamtv** [comment]
Vedo che da pochi minuti il reindirizzamento è stato corretto. Per il modulo di acquisto abbiamo capito che non si apre la finestra di pagamento perchè il browser è settato in lingua non italiana (dalle impostazioni del browser).

**Comment by blaso91** [comment]
Risolto in produzione
