### ISSUE TITLE
Acquisto OTO-1: feedback mancante

### ISSUE THREAD

**Issue by blaso91** [camtv/funnel#3]
Dopo aver acquistato il libro, si viene redirezionati alla pagina della OTO dove è possibile effettuare il pagamento one-click. Una volta effettuato il pagamento sul dialogo, non vi è alcun feedback relativo all'acquisto avvenuto con successo o fallito del prodotto.

**Comment by PaoloBrach** [comment]
In mattinata chiederò ad Abramo le modalità disponibili di feedback lato Camtv pay e aggiornerò immediatamente questo topic.

**Comment by PaoloBrach** [comment]
Dunque, lato cam.tv non viene offerto feedback, ho inoltre chiesto ad Alessio la possibilità di visionare una conferma su voluum o via popup ma mi è stto detto di non mostrare nessuna conferma e passare direttamente su oto-2. Scriverò dunque una piccolissima funzione che fa redirect a oto-2 a pagamento completato, come da indicazioni.

**Comment by PaoloBrach** [comment]
codice aggiornato, al successo redirigerà automaticamente a oto-2

**Comment by blaso91** [comment]
Risolto in produzione
