### ISSUE TITLE
Acquisto OTO-2: feedback mancante

### ISSUE THREAD

**Issue by blaso91** [camtv/funnel#4]
Dopo aver acquistato OTO-2 non vi è alcun feedback per l'utente. Forse è necessario reindirizzare ad una thank-you page oppure nascondere i bottoni di acquisto.

**Comment by PaoloBrach** [comment]
Alessio mi informa che la pagina finale deve essere inserita all'indirizzo: internetcreaindipendenza.it/thank-you
Mi dice inoltre che l'html da inserire è già in possesso di Ivan, che ora informerò. 
Nel frattempo inserisco il redirect a questo indirizzo nella oto-2, così quella è pronta.

**Comment by blaso91** [comment]
Risolto in produzione
